package com.nosql_tree.skill.application.services.crud;

import com.nosql_tree.skill.domain.exception.SkillAlreadyExistsException;
import com.nosql_tree.skill.domain.exception.SkillNotFoundException;
import com.nosql_tree.skill.domain.model.Skill;
import com.nosql_tree.skill.domain.ports.inbound.CreateSkillPort;
import com.nosql_tree.skill.domain.ports.outbound.SkillMongoRepositoryPort;
import com.nosql_tree.skill.domain.ports.outbound.SkillNeoRepositoryPort;
import jakarta.transaction.Transactional;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.HashSet;
import java.util.Optional;
import java.util.Set;

/**
 * CreateSkillService.java
 * <p>
 * Description: This service create the Skills and store in the MongoDB and Neo4j database.
 *
 * <ul>
 *     <li>{@code IllegalArgumentException}is throwing when the Slug generated is null</li>
 *     <li>{@code SkillAlreadyExistsException} is throwing when the Slug generated by label - name, is already in the database</li>
 *     <li>{@code SkillNotFoundException} is throwing when the Skill nodes prerequisites to unlock this new Skill is not found.</li>
 * </ul>
 *
 * @author aleja
 * @since 13/05/2026
 */

@Slf4j
@Service
public class CreateSkillService implements CreateSkillPort {
    private final SkillNeoRepositoryPort skillNeoRepositoryPort;
    private final SkillMongoRepositoryPort mongoRepositoryPort;

    public CreateSkillService(SkillNeoRepositoryPort skillNeoRepositoryPort, SkillMongoRepositoryPort mongoRepositoryPort) {
        this.skillNeoRepositoryPort = skillNeoRepositoryPort;
        this.mongoRepositoryPort = mongoRepositoryPort;
    }

    @Transactional
    @Override
    public void createSkill(Skill skill, Set<String> prerequisites){

        /// Make a copy to secure the correct creation of the Slug
        Skill newSkill = new Skill(skill);

        if(newSkill.getSlug() == null){
            log.info("The new skill cannot be null");
            throw new IllegalArgumentException("The Slug of the Skill cannot be null");
        }

        ///Verify if already exists an identical Slug -> label + - + name
        if(skillNeoRepositoryPort.existsBySlug(newSkill.getSlug())){
            log.info("The new skill cannot exists another skill with the same slug {}",newSkill.getSlug());
            throw new SkillAlreadyExistsException();
        }

        ///Verify that the prerequisites, that's slugs
        Set<String> preSkills = new HashSet<>();
        for(String slug: prerequisites){
            /// Extract and verify by the slugs
            Optional<Skill> optional =  skillNeoRepositoryPort.findBySlug(slug);

            if(optional.isEmpty()){
                log.info("The skill node prerequisite cannot be found");
                throw new SkillNotFoundException("The Skill node  prerequisite cannot be found");
            }
            preSkills.add(optional.get().getSlug());
        }

        skill.setRequirements(preSkills);

        mongoRepositoryPort.save(skill);
        skillNeoRepositoryPort.save(skill);
    }
}
