spring:
  application:
    name: nosql-tree
  data:
    mongodb:
      host: localhost
      port: 27017
      database: skilltree_db  # Forzamos el nombre fuera de la URI
    neo4j:
      uri: bolt://localhost:7687
      authentication:
        username: neo4j
        password: password123

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/v3/docs
server:
  port: 8080
debug: true
