package com.nosql_tree.user.domain.model;


import java.util.*;

/**
 * User.java
 * <p>
 * Description: Implementation of the basic user model saving the required id knows
 *
 * @author aleja
 * @since 06/05/2026
 */

public class User {
    private String id;
    private String name;
    private Set<String> completedSkills;

    ///UserAccount variables, use in the same clase for short time and more control of the document
    private String email;   // Represents the username in the login
    private String password; // Should be hashed
    private Role role;


    /// More info for MongoDB document
    private Map<String, Object> metadata;
    private String lastLogin;

    private int level;  //Actual level of advanced in the tree


    /**
     * This constructor is created for the translation of UserNode to User
     * @param id identifier generated by UUID
     * @param name username of the User or real name
     * @param level status of the growth in the skill tree
     */
    public User(String id, String name, int level) {
        this.id = id;
        this.name = name;
        this.level = level;
    }

    public User(String id, String name, String email, String password, Role role) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.role = role == null ? Role.USER : role;
        this.level = 1;
        this.completedSkills = new HashSet<>();
        this.metadata = new HashMap<>();
    }

    public User(String name, String email, String password, Role role) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.role = role == null ? Role.USER : role;
        this.level = 1;
        this.completedSkills = new HashSet<>();
        this.metadata = new HashMap<>();
    }

    public User(String id, String name, Set<String> completedSkills, String email, String password, Role role, Map<String, Object> metadata, String lastLogin, int level) {
        this.id = id;
        this.name = name;
        this.completedSkills = completedSkills;
        this.email = email;
        this.password = password;
        this.role = role;
        this.metadata = metadata;
        this.lastLogin = lastLogin;
        this.level = level;
    }



    public User() {
        role = Role.USER;
        completedSkills = new HashSet<>();
    }

    /// This constructors are created for test purpose
    public User(String userId, String name, Set<String> completedSkills) {
        this.id = userId;
        this.name = name;
        this.completedSkills = completedSkills;
        this.email = "testmail";
        this.password= "testPass";
        this.role=Role.USER;
        this.metadata = new HashMap<>();
        this.lastLogin = "1/01/2026";
        this.level = 1;
    }

    public User(String name) {
        this.name = name;
        this.completedSkills = new HashSet<>();
        this.email = "testmail";
        this.password= "testPass";
        this.role= Role.USER;
        this.metadata = new HashMap<>();
        this.lastLogin = "1/01/2026";
        this.level = 1;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<String> getCompletedSkills() {
        return completedSkills;
    }

    public void setCompletedSkills(Set<String> completedSkills) {
        this.completedSkills = completedSkills;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public Map<String, Object> getMetadata() {
        return metadata;
    }

    public void setMetadata(Map<String, Object> metadata) {
        this.metadata = metadata;
    }

    public String getLastLogin() {
        return lastLogin;
    }

    public void setLastLogin(String lastLogin) {
        this.lastLogin = lastLogin;
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }
}
